name: bayes-opt-battle
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - anyio=3.7.0
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.12.1
  - backcall=0.2.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2020.6.20
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - comm=0.1.3
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.1
  - executing=0.8.3
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=2.0.0
  - importlib_resources=5.2.0
  - ipykernel=6.23.1
  - ipython=8.14.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - jedi=0.18.2
  - jinja2=3.0.3
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.3
  - jupyter_core=4.12.0
  - jupyter_server=1.13.5
  - jupyterlab=3.3.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=3.0.7
  - krb5=1.20.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=12.0.0
  - libcxx=16.0.6
  - libedit=3.1.20210910
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.2.0
  - libglib=2.76.3
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm12=12.0.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libpq=12.15
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.2
  - mistune=3.0.0
  - nbclassic=0.5.6
  - nbconvert=5.5.0
  - nbformat=5.1.3
  - ncurses=6.4
  - nest-asyncio=1.5.1
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - nspr=4.33
  - nss=3.74
  - numpy=1.25.0
  - openssl=3.1.1
  - packaging=21.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.1.2
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.0.4
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytz=2023.3
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - send2trash=1.8.0
  - setuptools=67.7.2
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.3.0
  - sqlite=3.38.5
  - stack_data=0.2.0
  - terminado=0.17.1
  - testpath=0.5.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2023c
  - urllib3=2.0.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.6.0
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.13
  - zstd=1.5.2
